---
# Install Joplin desktop client
- name: Install_desktop | Include appimage installation role.
  ansible.builtin.include_role:
    name: appimage
  vars:
    appimage_download_urls:
      - url: "{{ joplin_client_desktop_appimage_url }}"
        name: joplin-desktop
        state: present

- name: Install_desktop | Manage config directories.
  ansible.builtin.file:
    state: directory
    path: "{{ joplin_dir_user_config }}"
    owner: "{{ joplin_user }}"
    group: "{{ joplin_user }}"
    mode: '0755'
