---
# tasks file for joplin
- name: Main | Include install_cli tasks.
  ansible.builtin.include_tasks: install_cli.yml
  when: joplin_client_cli|bool

- name: Main | Manage joplin desktop.
  when: joplin_client_desktop|bool
  block:
    - name: Main | Include install_desktop tasks.
      ansible.builtin.include_tasks: install_desktop.yml
    - name: Main | Include install_plugins tasks.
      ansible.builtin.include_tasks: install_plugins.yml
    - name: Main | Include config_desktop tasks
      ansible.builtin.include_tasks: config_desktop.yml

- name: Main | Include install_tools tasks
  ansible.builtin.include_tasks: install_tools.yml
  when: joplin_install_tools|bool
...
