---
- name: Install_cli | Converge
  hosts: all
  tasks:

    - name: "Converge | Include variables"
      ansible.builtin.include_vars: variables.yml

    - name: "Converge | Include role spreadcat.joplin"
      ansible.builtin.include_role:
        name: "spreadcat.joplin"
