---
- name: Converge
  hosts: all
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: INLCUDE VARIABLES
      ansible.builtin.include_vars: ../../defaults/main.yml
    - name: INCLUDE VARIABLES
      ansible.builtin.include_vars: ./variables.yml
    - name: INCLUDE SPREADCAT.JOPLIN
      ansible.builtin.include_role:
        name: "spreadcat.joplin"
