---
- name: Molecule | Converge
  hosts: all
  tasks:
    - name: "Converge | Include variables."
      ansible.builtin.include_vars: variables.yml

    - name: "Converge | Include joplin role."
      ansible.builtin.include_role:
        name: "spreadcat.joplin"
